services:
  postgres-mlflow:
    image: postgres:15
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow"]
      interval: 5s
      retries: 10

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    depends_on:
      postgres-mlflow:
        condition: service_healthy
    environment:
      MLFLOW_BACKEND_STORE_URI: postgresql+psycopg2://mlflow:mlflow@postgres-mlflow/mlflow
      MLFLOW_ARTIFACTS_DESTINATION: file:///mlflow/mlruns
    volumes:
      - ./mlruns:/mlflow/mlruns
    ports:
      - "5000:5000"

  api:
    image: ${API_IMAGE:-local/solar-flares-api:test}
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MODEL_NAME: solar-flares-classifier
      MODEL_ALIAS: Production
    depends_on:
      - mlflow
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ready"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - ./mlruns:/mlflow/mlruns
