name: CD (build -> GHCR)   # <- on retire le mot "deploy" du nom pour éviter la confusion

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}/api
    steps:
      - uses: actions/checkout@v4
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: api
          file: api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  # ⬇️ JOB DEPLOY DÉSACTIVÉ TANT QU'ON N'A PAS DE SERVEUR/SECRETS
  deploy:
    if: ${{ secrets.SSH_HOST != '' && secrets.SSH_USER != '' && secrets.SSH_KEY != '' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Secrets SSH détectés → réactive tes étapes SSH ici."
