name: CI (build + smoke)

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: local/solar-flares-api:test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (Optionnel) tests unitaires Python si tu en as
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (optional)
        run: |
          if [ -f api/requirements.txt ]; then
            pip install -r api/requirements.txt pytest
          fi

      - name: Run unit tests (optional)
        run: |
          if [ -d tests ] || [ -d api/tests ]; then
            pytest -q || true
          fi

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image (no push)
        uses: docker/build-push-action@v6
        with:
          context: api
          file: api/Dockerfile
          load: true
          tags: ${{ env.IMAGE_TAG }}

      - name: Launch minimal stack (mlflow + api)
        env:
          API_IMAGE: ${{ env.IMAGE_TAG }}
        run: |
          docker compose -f docker-compose.ci.yml up -d
          # Attente simple
          for i in {1..60}; do
            if curl -sf http://localhost:8000/ready >/dev/null; then
              echo "API ready"; break
            fi
            sleep 2
          done

      - name: Smoke tests
        run: |
          set -e
          curl -fsS http://localhost:8000/health >/dev/null
          curl -fsS http://localhost:8000/ready  >/dev/null
          curl -fsS http://localhost:8000/model-info | head -c 200 || true

      - name: Show logs on failure
        if: failure()
        run: |
          docker compose -f docker-compose.ci.yml logs --no-color || true

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.ci.yml down -v
